### ISSUE TITLE
Concerning the entity representation

### ISSUE THREAD

**Issue by DexterZeng** [nitishgupta/neural-el#3]
Hi, thank you for sharing the code.
I am actually interested in the vector representations of entities and I wonder how can I generate the entity embedding described in the paper? 
Many thanks,
Weixin.

**Comment by nitishgupta** [comment]
Hi! Thank you for you interest. You can train the complete model which is a lot of effort. I can instead give you the trained entity embeddings from a learned model. Give a couple of days and I'll get back to you.
