### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_tokens'

### ISSUE THREAD

**Issue by loveJasmine** [nitishgupta/neural-el#4]
WARNING:ccg_nlpy.pipeline_config:Models not found. To use pipeline locally, please refer the documentation for downloading models.
INFO:ccg_nlpy.pipeline_config:Using pipeline web server with API: http://austen.cs.illinois.edu:5800
INFO:ccg_nlpy.remote_pipeline:pipeline has been set up
Loading Glove Word Vocabulary
Loading Type Label Vocabulary
Loading Known Entity Vocabulary ... 
Loading wid2Wikititle
Loading Coherence Strings Dicts ... 
Loading Crosswikis dict. (takes ~2 mins to load)
Crosswikis loaded. Size: 37650380
Loading Glove Word Vectors
[#] Glove Vectors loaded!
[#] Test Mentions File : neural-el_resources/sampletest.txt
[#] Loading test file and preprocessing ... 
WARNING:ccg_nlpy.remote_pipeline:Unexpected status code 503, please open an issue on GitHub for further investigation.
Traceback (most recent call last):
  File "neuralel.py", line 240, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "neuralel.py", line 89, in main
    coherence=FLAGS.coherence)
  File "/home/mldl/ub16_prj/neural-el/readers/inference_reader.py", line 65, in __init__
    self.processTestDoc(test_mens_file)
  File "/home/mldl/ub16_prj/neural-el/readers/inference_reader.py", line 102, in processTestDoc
    self.doc_tokens = self.ccgdoc.get_tokens
AttributeError: 'NoneType' object has no attribute 'get_tokens'

**Comment by nitishgupta** [comment]
Please change the server to: http://macniece.seas.upenn.edu:4001
That should work.

**Comment by loveJasmine** [comment]
404 Not found

**Comment by loveJasmine** [comment]
BTW, would you pan to open the training code?

**Comment by nitishgupta** [comment]
Are you able to access this URL in the web-browser:
http://macniece.seas.upenn.edu:4001/annotate?text=%22My%20name%20is%20Nitish%22&views=POS

The training code is really messy, and in a old version of tensorflow. If I were to, I'd re-write it in allennlp. It should be fairly simple, but I won't get time for that in a month or two.

**Comment by loveJasmine** [comment]
sure, expecting and thanks
